version: '3'
services:

  laravel-api:
    image: dragoono/laravel-api:1.0.2
    container_name: laravel-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-api.rule=Host(`laravel-api.devnik.dev`)"
      - "traefik.http.routers.laravel-api.entrypoints=websecure"
      - "traefik.http.routers.laravel-api.tls.certresolver=devnik-resolver"
    networks:
      - proxy
    environment:
      TZ: Europe/Berlin
      APP_URL: http://localhost
      APP_ENV: local

#Docker Networks
networks:
  proxy:
    external:
      name: "traefik_proxy"
